### Set the graph base url
@graph=https://graph.microsoft.com/v1.0
@tenanat=integrationsonline
@user=alexander.pajer@integrations.at

# Autenticate User
# @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}

### Get the list of all teams you are a member of
# @name teams
GET https://graph.microsoft.com/v1.0/users/{{user}}/joinedTeams
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

### Get the list of channels in a team
GET https://graph.microsoft.com/v1.0/teams/{{teams.response.body.value[0].id}}/channels
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json


### Post a message to a channel
POST https://graph.microsoft.com/v1.0/teams/{{teams.response.body.value[0].id}}/channels/19:3b24bc6a4480445a9fa6e4b7fcca122b@thread.skype/messages'
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json


###
POST http://localhost:7071/api/postToTeams
Content-Type: application/json

{
    "teamsId": "{{teams.response.body.value[0].id}}",
    "channelId": "19:3b24bc6a4480445a9fa6e4b7fcca122b@thread.skype",
    "message": "Hello World"
}