# Build Image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "net-config.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "net-config.dll"]

# Build Image
# docker build --rm -f dockerfile -t net-config .

# Run Image without env vars
# docker run -it --rm -p 5051:80 net-config
# Run Image with env vars
# docker run -it --rm -p 5051:80 net-config -e "App__UseEnv"="true" "Azure__TenantId"="d92b0000-90e0-4469-a129-6a32866c0d0a" 

# Browse using: 
# http://localhost:5051/

# Publish Image to dockerhub
# docker tag net-configarambazamba/net-config
# docker push arambazamba/net-config