@notificationUrl="https://m10-graphevents-23196.vault.azure.net/secrets/graphConStr?tenantId=integrations.at"

# @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}

POST https://graph.microsoft.com/v1.0/subscriptions HTTP/1.1
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
    "changeType": "created,updated",
    "notificationUrl": {{notificationUrl}},
    "resource": "/me/mailfolders('inbox')/messages",
    "expirationDateTime": "2022-05-07T11:00:00.0000000Z",
    "clientState": "SecretClientState"
}