### Start orchestration 
# @name orch
POST http://localhost:7071/api/cart/init HTTP/1.1
content-type: application/json

{
    "Id": "5c60fe1d-9851-47ca-aab9-622ca857ea29",
    "Total": 0,
    "Customer": {
        "Name": "John Doe",
        "Address": "123 Main Street, Seattle, WA 98101",
        "EMail": "alexander.pajer@integrations.at"
    },
    "Items": []              
}

### Add Blini with Salmon
POST   http://localhost:7071/api/cart/add HTTP/1.1
content-type: application/json

{
    "id": 2,
    "name": "Blini with Salmon",
    "price": 9,
    "quantity": 2,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Get Orchestration State using statusQueryGetUri
GET {{orch.response.body.statusQueryGetUri}} HTTP/1.1

### Add Butter Chicken
POST   http://localhost:7071/api/cart/add HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "Butter Chicken",
    "price": 12,
    "quantity": 1,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Remove Blini with Salmon
DELETE    http://localhost:7071/api/cart/remove HTTP/1.1
content-type: application/json

{
    "id": 2,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Complete 
POST   http://localhost:7071/api/cart/complete HTTP/1.1
content-type: application/json

{
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}
