### Start orchestration 
# @name orch
GET  http://localhost:7071/api/cart/start HTTP/1.1
content-type: application/json

### Add Blini with Salmon
POST   http://localhost:7071/api/cart/add HTTP/1.1
content-type: application/json

{
    "id": 2,
    "name": "Blini with Salmon",
    "price": 9,
    "quantity": 2,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Get Orchestration State using statusQueryGetUri
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orch.response.body.id}}?taskHub=TestHubName&connection=Storage&code=HMgEzb81Rwgw2QttmMQQHTXTHxrlBPE06wt8FyW7WpsOMxgS6pP0Yw== HTTP/1.1

### Add Butter Chicken
POST   http://localhost:7071/api/cart/add HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "Butter Chicken",
    "price": 12,
    "quantity": 1,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Remove Blini with Salmon
DELETE    http://localhost:7071/api/cart/remove HTTP/1.1
content-type: application/json

{
    "id": 2,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Complete 
POST   http://localhost:7071/api/cart/complete HTTP/1.1
content-type: application/json

{
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}
