### Start orchestration 

# @name orch
GET  http://localhost:7071/api/food/start HTTP/1.1
content-type: application/json

###
# -> make rest call to statusQueryGetUri

GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orch.response.body.id}}?taskHub=TestHubName&connection=Storage&code=HMgEzb81Rwgw2QttmMQQHTXTHxrlBPE06wt8FyW7WpsOMxgS6pP0Yw== HTTP/1.1

### Add chips
POST   http://localhost:7071/api/food/update HTTP/1.1
content-type: application/json

{
    "ID": 1,
    "Name": "Chips",
    "Amount": 5,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/chips.jpeg",
    "Enabled": true,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Add fish
POST   http://localhost:7071/api/food/update HTTP/1.1
content-type: application/json

{
    "ID": 2,
    "Name": "Fish",
    "Amount": 3,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/fish.jpeg",
    "Enabled": false,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Complete 
POST   http://localhost:7071/api/food/complete HTTP/1.1
content-type: application/json

{"OrchestrationInstanceId": "39c7bfba4026465e99ea5e653fd89b65"}
