### Start orchestration 

GET  http://localhost:7071/api/food/start-collection HTTP/1.1
content-type: application/json

###

# -> replace OrchestrationInstanceId in subsequent rest calls
# -> make rest call to statusQueryGetUri

GET http://localhost:7071/runtime/webhooks/durabletask/instances/d3b1cc41a94c4ec1b74d1cbf510f8d6c?taskHub=TestHubName&connection=Storage&code=HMgEzb81Rwgw2QttmMQQHTXTHxrlBPE06wt8FyW7WpsOMxgS6pP0Yw== HTTP/1.1

### Add chips

POST   http://localhost:7071/api/food/update HTTP/1.1
content-type: application/json

{
    "ID": 1,
    "Name": "Chips",
    "Amount": 5,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/chips.jpeg",
    "Enabled": true,
    "OrchestrationInstanceId": "d3b1cc41a94c4ec1b74d1cbf510f8d6c"
}

### Add fish

POST   http://localhost:7071/api/food/update HTTP/1.1
content-type: application/json

{
    "ID": 2,
    "Name": "Fish",
    "Amount": 3,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/fish.jpeg",
    "Enabled": false,
    "OrchestrationInstanceId": "d3b1cc41a94c4ec1b74d1cbf510f8d6c"
}

### Delete fish

DELETE http://localhost:7071/api/food/update HTTP/1.1
content-type: application/json

{
    "ID": 2,
    "Name": "Fish",
    "Amount": 3,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/fish.jpeg",
    "Enabled": false,
    "OrchestrationInstanceId": "d3b1cc41a94c4ec1b74d1cbf510f8d6c"
}

### Complete 

POST   http://localhost:7071/api/food/complete HTTP/1.1
content-type: application/json

{"OrchestrationInstanceId": "d3b1cc41a94c4ec1b74d1cbf510f8d6c"}
