
### get products
GET http://localhost:7071/api/products HTTP/1.1
content-type: application/json


### create product
POST  http://localhost:7071/api/products HTTP/1.1
content-type: application/json

{
    "name": "Azure Skills",
    "price": 22
}