apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-keyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "az-native-kv-dev"
  - name: azureTenantId
    value: "d92b247e-90e0-4469-a129-6a32866c0d0a"
  - name: azureClientId
    value: "7f0aee9d-4380-4db8-a16d-b3197acab3a4"
  - name: azureClientSecret
    value: "K~b8Q~V5iAjkya8TMfIRWbeiOKZrxjJzxoq38bX-"