### Test Hello World Function
@url=https://func-aca.greenisland-f200acc8.westeurope.azurecontainerapps.io

POST {{url}}/api/acatrigger
Content-Type: application/json

{
    "name": "Azure"
}

### Test YouTube Transcribe Function
@url=https://youtube-transcribe.greenisland-f200acc8.westeurope.azurecontainerapps.io
POST {{url}}/api/do_transcribe
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=9bZkp7q19f0"
}