### Test Hello World Function
@url=https://aca-trigger-func.greenisland-f200acc8.westeurope.azurecontainerapps.io

POST {{url}}/api/acatrigger
Content-Type: application/json

{
    "name": "Azure"
}

### Test YouTube Transcribe Function
@url=https://aca-youtube-transcriber.redisland-788712ff.westeurope.azurecontainerapps.io

POST {{url}}/api/get_transcription HTTP/1.1
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=vYjAg27aHkA&t=1570s",
    "lang": "german",    
    "length": "detailed"
}