##### Stage 1 - Create the build-image
FROM node:18-alpine as build
LABEL author="Alexander Pajer"

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

##### Stage 2 - Create the run-time-image
FROM nginx:alpine
VOLUME /var/cache/nginx

# Take output from node build
COPY --from=build /app/dist/msal-easy-auth/browser/ /usr/share/nginx/html
# Add nginx url rewriteconfig
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

# docker build --rm -f dockerfile -t msal-easy-auth .
# docker run -d --rm -p 5051:80 msal-easy-auth

# browse using http://localhost:5051/

# Publish Image to dockerhub
# docker tag msal-easy-auth arambazamba/msal-easy-auth
# docker push arambazamba/msal-easy-auth
