FROM node:latest
WORKDIR /frontend
COPY package.json ./

RUN npm i
COPY . .

EXPOSE 8088
CMD [ "node", "server.js" ]

# Build

# docker build -t arambazamba/node-app:1.19.0 .
# docker run -p 8090:80 -d arambazamba/node-app:1.19.0
# docker push arambazamba/node-app:1.19.0