@user=alexander.kastil@integrations.at
@subscriptionId=78033352-805c-4acd-af80-f8f95083268d
@resourceGroup=vouchers-app-dev
@partnerTopic=graph-events-dev
@location=westeurope
@endDate=2024-03-01

@notificationUrl=EventGrid:?azuresubscriptionid={{subscriptionId}}&resourcegroup={{resourceGroup}}&partnertopic={{partnerTopic}}&location={{location}}

# @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}

### subscribe change notifications
POST https://graph.microsoft.com/v1.0/subscriptions HTTP/1.1
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
    "changeType": "created",
    "notificationUrl": "{{notificationUrl}}",
    "lifecycleNotificationUrl": "{{notificationUrl}}",
    "resource": "/users/{{user}}/mailfolders('inbox')/messages",
    "expirationDateTime": "{{endDate}}T11:00:00.0000000Z",
    "clientState": "SecretClientState"
}