# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /build
COPY . .
RUN dotnet restore "catalog-service.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "catalog-service.dll"]

# Build Image
# docker build --rm -f dockerfile -t catalog-service .

# Run Image without env vars
# docker run -it --rm -p 5051:8080 catalog-service

# Run Image with env vars
# docker run -it --rm -p 5051:8080 catalog-service -e "App:UserSQLite=true" -e "App:ConnectionStrings:SQLServerConnection=<SQLSERVER_CONNECTION_STRING>"

# Browse using: 
# http://localhost:5051
# http://localhost:5051/food
# http://localhost:5051/config

# Publish Image to dockerhub
# docker tag catalog-service arambazamba/catalog-service
# docker push arambazamba/catalog-service