@topicurl=foodevents-28791.westeurope-1.eventgrid.azure.net
@topickey=xR9JDq+BGD+Pixo9eijVRjAPev1J9xOJgGr7qHHNiiw=
@timestamp=new Date().toISOString().split('.')[0] + 'Z'

@id=$guid.ToString()

POST  https://{{topicurl}}//api/events HTTP/1.1
content-type: application/cloudevents+json; charset=utf-8
aeg-sas-key: {{topickey}}

{
   "specversion":"1.0",
   "type":"foodapp.order.accepted",
   "source":"foodapp",
   "id": "5c60fe1d-9851-47ca-aab9-622ca857ea23",
   "time": "2022-11-01T08:41:19Z",
   "datacontenttype":"application/json",
   "data":{
      "id": "5c60fe1d-9851-47ca-aab9-622ca857ea29",
      "customerId": "7c5fe5c7-1b03-469b-8c71-13823d6a8049",
      "customerName": "John Doe",
      "address": "123 Main Street, Seattle, WA 98101",
      "status": "incoming",
      "items": [
         {
            "name": "butter chicken",
            "quantity": 2
         },
         {
            "name": "badam kheer",
            "quantity": 1
         }
      ]
   }
}