# Build Image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "food-api.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "food-api.dll"]

# Build Image
# docker build --rm -f "dockerfile" -t foodapi .

# Run Image
# docker run -it --rm -p 5051:80 foodapi

# Browse using: 
# http://localhost:5051/food

# Publish Image to dockerhub
# docker tag foodapi arambazamba/foodapi
# docker push arambazamba/foodapi