### Start orchestration 
# @name orch
GET  http://localhost:7071/api/foodcart/start HTTP/1.1
content-type: application/json

### Add chips
POST   http://localhost:7071/api/foodcart/add HTTP/1.1
content-type: application/json

{
    "ID": 1,
    "Name": "Chips",
    "Amount": 5,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/chips.jpeg",
    "Enabled": true,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Get Orchestration State using statusQueryGetUri
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orch.response.body.id}}?taskHub=TestHubName&connection=Storage&code=HMgEzb81Rwgw2QttmMQQHTXTHxrlBPE06wt8FyW7WpsOMxgS6pP0Yw== HTTP/1.1

### Add fish
POST   http://localhost:7071/api/foodcart/add HTTP/1.1
content-type: application/json

{
    "ID": 2,
    "Name": "Fish",
    "Amount": 3,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/fish.jpeg",
    "Enabled": false,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Remove chips
DELETE    http://localhost:7071/api/foodcart/delete HTTP/1.1
content-type: application/json

{
    "ID": 1,
    "Name": "Chips",
    "Amount": 5,
    "PictureUrl": "https://foodpics6743.blob.core.windows.net/processed/chips.jpeg",
    "Enabled": true,
    "OrchestrationInstanceId": "{{orch.response.body.id}}"
}

### Complete 
POST   http://localhost:7071/api/foodcart/complete HTTP/1.1
content-type: application/json

{"OrchestrationInstanceId": "{{orch.response.body.id}}"}
