# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "food-api-dapr.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "food-api-dapr.dll"]

# Build Image
# docker build --rm -f dockerfile -t food-api-dapr .

# Run Image without env vars
# docker run -it --rm -p 5051:80 food-api-dapr

# Browse using: 
# http://localhost:5051/

# Publish Image to dockerhub
# docker tag food-api-dapr alexander-kastil/food-api-dapr
# docker push alexander-kastil/food-api-dapr