@baseUrl = http://localhost:5010/v1.0/invoke/food-api/method

### module: dapr-intro
### Consume the api using the dapr sidecar
GET {{baseUrl}}/food HTTP/1.1

### module: statestore-aca
### Get the count and increment it by 1
GET {{baseUrl}}/count/get 
content-type: application/json

### reset the count
GET {{baseUrl}}/count/reset 
content-type: application/json

### module: secrets-config
### Get secret
GET {{baseUrl}}/config/getKeyVaultSecret?secretName=aiConStr
content-type: application/json

### Get config
GET {{baseUrl}}/config/getAppConfig?configKey=CustomConfigValue
content-type: application/json

### module: pubsub
### Add a food item to pubsub -> returns http 204
POST {{baseUrl}}/food/add  HTTP/1.1
content-type: application/json

{
    "id": 15,
    "name": "Pad Kra Pao",
    "price": 12.0,
    "inStock": 9,
    "pictureUrl": null,
    "code": "kra"
}
