name: catalog-api-cicd

on:
  push:
    branches:
      - master
    paths:
      - app/food-catalog-api/**

  # allows manual execution of workflow
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true       
env:
  appservice: food-catalog-api-github-actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build with dotnet
        run: dotnet build ${{ github.workspace }}/apps/catalog-api/catalog-api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ github.workspace }}/apps/catalog-api/catalog-api.csproj -c Release -o ${{env.DOTNET_ROOT}}/api
                        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.appservice }}
          publish-profile: ${{ secrets.CATALOG_API_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/api
