### Send Hubertus

POST  http://localhost:7071/api/vsCodeTrigger HTTP/1.1
content-type: application/json

{
    "name": "Hubertus"
}

### Send Max
POST  http://localhost:7071/api/vsCodeTrigger HTTP/1.1
content-type: application/json

{
    "name": "Max"
}